apiVersion: v1
kind: Service
metadata:
  name: app-prod
  namespace: finalapp-prod
spec:
  selector:
    app: finalapp-prod
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 50100
    protocol: TCP