apiVersion: v1
kind: Service
metadata:
  name: app-nonprod
  namespace: finalapp-nonprod
spec:
  selector:
    app: finalapp-nonprod
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 50000
    protocol: TCP